version: '3.9'

services:
  app:
    build: ../
    environment:
      MYSQL_TRACKIT_CONNECTION_STRING: "Server=localhost;Port=3306;Database=trackitservice;User=root;Password=password;SSL Mode=None;"
    depends_on:
      - mysql
    links:
      - mysql
  
  mysql:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: trackitservice
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
    ports:
      - "3306:3306"
    
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:8080"

networks:
  trackIt:
    driver: bridge
    name: trackIt