version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - trackIt
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - trackIt

networks:
  trackIt:
    driver: bridge
    name: trackIt