version: '3.9'
x-project-name: &project-name docker-compose-itrackit
name: *project-name

networks:
  trackIt:
    driver: bridge
    name: trackIt

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - trackIt
  
  mysql:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: trackitservice
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
    ports:
      - "3306:3306"
    networks:
      - trackIt
    
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - trackIt