name: CI

on: ['push', 'pull_request']

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Build application
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Run unit tests
        run: |
          dotnet test ./service/TrackIt.Tests/TrackIt.Tests.csproj --filter "FullyQualifiedName~Unit"

      - name: Run integration tests
        run: |
          TEST_PROJECT_PATH="./service/TrackIt.Tests/Integration"
          
          for TEST_FILE in $(find $TEST_PROJECT_PATH -type f -name "*Tests.cs"); do
            TEST_NAME=$(basename $TEST_FILE .cs)
          
            echo "Running tests in $TEST_FILE"
            dotnet test ./service/TrackIt.Tests/TrackIt.Tests.csproj --filter "FullyQualifiedName~$TEST_NAME"
          done

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image for docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vitchenzo/docker-compose-deps-app:4461440d645f